Replace the youtube API with web scrapping
stealthanthrax/kasper_music_player pull request #32
Opened 2019-01-16 18:47 UTC by SLakhani1

Used web scrapping as replacement of API.

## Description
youtube_search(): It searches the query on youtube and returns the links of all the results.
youtube_related(): It opens the first link returned by youtube_search() and returns the links of all the videos present in the related videos section.

## Motivation and Context

Issue: #21 

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-01-16 18:53 UTC, sansyrox requested changes
Please check the inline comments. 
Otherwise, a great job with the PR 🚀 🚀

2019-01-16 18:53 UTC, stealthanthrax commented on server/modules/youtube_videos.py
> +import webbrowser, requests, sys, bs4, re
Please shift the imports to a single line. It improves the readability of code.

2019-01-16 18:53 UTC, stealthanthrax commented on server/modules/youtube_videos.py
> +
Remove the extra lines, leaving an eof.

2019-01-17 09:21 UTC, SLakhani1 commented on server/modules/youtube_videos.py
> +
Done

2019-01-17 09:29 UTC, sansyrox approved these changes

2019-01-17 09:29 UTC, merged